title: Technoramic 5190
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://MMICDSRobotics.github.com/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact
 - title: Robot
   url: /robot
 - title: Programming
   url: /programming

social:
   github: MICDSRobotics
   twitter: technoramic5190
   facebook: technoramic5190
   email: micdsrobotics@gmail.com

google_analytics: "UA-58263416-1"
